name: Crash to Desktop
description: For issues that cause the game to crash to desktop (CTD) (用于游戏崩溃至桌面的问题)
title: "Country Affected - Short Description of Issue (受影响的国家 - 问题简短描述)"
labels: Crash

body:
  - type: input
    id: OS
    attributes:
      label: Operating System (操作系统)
      placeholder: ex. Windows 11, macOS Monterey (示例：Windows 11, macOS Monterey)
    validations:
      required: true
  - type: input
    id: HOI4_version
    attributes:
      label: HOI4 version (HOI4版本)
      placeholder: Do NOT write latest version. ex. 1.15.3 (请勿填写最新版本，例如要写 1.15.3)
    validations:
      required: true
  - type: input
    id: TNO_version
    attributes:
      label: TNO version (TNO版本)
      placeholder: Do NOT write latest version. ex. 1.7.0 (请勿填写最新版本，例如要写 1.7.0)
    validations:
      required: true
  - type: input
    id: TOT_version
    attributes:
      label: TOT version (TOT版本)
      placeholder: Do NOT write latest version. ex. 1.6c (请勿填写最新版本，例如要写 1.6c)
    validations:
      required: true
  - type: input
    id: other_mods
    attributes:
      label: Do you have other mods in use? (您是否使用了其他模组？)
      description: "Write none if you only have TNO enabled. (如果只有启用TNO，请写“none”)"
      placeholder: ex. The Moe Order (示例：The Moe Order)
    validations:
      required: true
  - type: dropdown
    id: steam
    attributes:
      label: Were you using Steam? (您是否使用了Steam？)
      options:
        - 'Yes (是)'
        - 'No (否)'
    validations:
      required: true
  - type: dropdown
    id: expansion
    attributes:
      label: Which major expansions do you NOT have? (您没有哪些大型扩展包？)
      description: Click all expansions that you don't have. (选择您没有的所有扩展包。)
      multiple: true
      options:
        - 'I have all (我有所有扩展包)'
        - 'MTG (MTG)'
        - 'LAR (LAR)'
        - 'NSB (NSB)'
        - 'BBA (BBA)'
        - 'AAT (AAT)'
        - 'TOA (TOA)'
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: Files (文件)
      description: |
        Link(s) to any log files / save games that may help debug your issue. (提供任何可能有助于调试问题的日志文件或存档文件的链接。)
        The most important ones are game.log and error.log (最重要的文件是 game.log 和 error.log)
        Log files can be found under Documents\Paradox Interactive\Hearts of Iron IV\logs (日志文件位于 Documents\Paradox Interactive\Hearts of Iron IV\logs)
        Save games can be found under Documents\Paradox Interactive\Hearts of Iron IV\save games (存档文件位于 Documents\Paradox Interactive\Hearts of Iron IV\save games)
      placeholder: (请提供文件链接)
    validations:
      required: true
  - type: textarea
    id: bugdesc
    attributes:
      label: Describe the crash (描述崩溃)
      description: |
        A clear and concise description of what the crash looks like (清晰简洁地描述崩溃的情况)
      placeholder: (请简要描述崩溃情况)
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce / Cause of the crash (重现步骤 / 崩溃原因)
      description: Tell us how we can reproduce / fix this crash (告诉我们如何重现此崩溃 / 修复此崩溃)
      placeholder: |
        1. Go to ...  (1. 进入...)
        2. Click on ...  (2. 点击...)
        3. Scroll down to ...  (3. 滚动到...)
        4. See error  (4. 看到错误)
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (截图)
      description: If applicable, add screenshots to help explain your problem. (如果适用，请添加截图以帮助解释您的问题。)
      placeholder: (如果有，上传截图)
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information (其他信息)
      description: Add any other context about the problem here (在此添加有关问题的其他背景信息)
      placeholder: (如果有，请提供其他信息)
    validations:
      required: false
